services:
  - type: web
    name: botirisatest
    runtime: python
    pythonVersion: 3.12.0          # ✅ set version here
    buildCommand: |
      export CARGO_HOME=$HOME/.cargo
      pip install -r requirements.txt
    startCommand: python bot.py     # adjust if your main file is different
